name: go-test
on:
  push:
    tags:
      - v*
    branches-ignore:
      - 'doc-*'
      - 'doc/*'
  pull_request:
    branches:
      - main
      - master
      - release
jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - uses: actions/checkout@v2
      - name: go-test
        run: go test -v ./...
